name: Code Review

on:
  push:
  pull_request:

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Verificar regras
        run: node .github/scripts/review.js
